#!/bin/bash

# Number of nodes and cores to use
nodes=1
cores=8

# Make the mesh using blockMesh (serial)
blockMesh 2>&1 | tee log.blockMesh

# Decompose the mesh and solution files (serial)
decomposePar 2>&1 | tee log.decomposePar

# Run the solver (parallel)
# mpirun -np $(($nodes*$cores)) fastPisoSolver -parallel 2>&1 | tee log.fastPisoSolver
mpirun -np $(($nodes*$cores)) pisoFoamTurbine -parallel 2>&1 | tee log.pisoFoamTurbine